# Full suite of mock_uss instances, capable of serving all local uss_qualifier tests.
# Requires the interoperability ecosystem that can be brought up with build/dev/run_locally.sh

# To bring up this system, see README.md

version: '3.8'

services:

  mock_uss_scdsc_a:
    container_name: mock_uss_scdsc_a
    hostname: scdsc.uss1.localutm
    image: interuss/monitoring
    command: mock_uss/start.sh
    environment:
      - MOCK_USS_AUTH_SPEC=DummyOAuth(${XSV_URL}/auth/token,uss1)
      - MOCK_USS_DSS_URL=${XSV_URL}
      - MOCK_USS_PUBLIC_KEY=/var/test-certs/auth2.pem
      - MOCK_USS_TOKEN_AUDIENCE=scdsc.uss1.localutm,localhost,host.docker.internal,${XSV_AUD:-}
      - MOCK_USS_BASE_URL=${XSV_URL}/muss_a
      # TODO: remove interaction_logging once dedicated mock_uss is involved in tests
      - MOCK_USS_SERVICES=scdsc,versioning,interaction_logging,flight_planning
      - MOCK_USS_INTERACTIONS_LOG_DIR=output/scdsc_a_interaction_logs
      - MOCK_USS_PORT=80
    expose:
      - 80
    ports:
      - 8074:80
    volumes:
      - ../../build/test-certs:/var/test-certs:ro
      - ./output/scdsc_a_interaction_logs:/app/monitoring/mock_uss/output/scdsc_a_interaction_logs
    user: "${UID_GID}"
    restart: always
    networks:
      - interop_ecosystem_network
    extra_hosts:
      - host.docker.internal:host-gateway

  mock_uss_scdsc_b:
    container_name: mock_uss_scdsc_b
    hostname: scdsc.uss2.localutm
    image: interuss/monitoring
    command: mock_uss/start.sh
    environment:
      - MOCK_USS_AUTH_SPEC=DummyOAuth(${XSV_URL}/auth/token,uss2)
      - MOCK_USS_DSS_URL=${XSV_URL}
      - MOCK_USS_PUBLIC_KEY=/var/test-certs/auth2.pem
      - MOCK_USS_TOKEN_AUDIENCE=scdsc.uss2.localutm,localhost,host.docker.internal,${XSV_AUD:-}
      - MOCK_USS_BASE_URL=${XSV_URL}/muss_b
      - MOCK_USS_SERVICES=scdsc,versioning,flight_planning
      - MOCK_USS_PORT=80
    expose:
      - 80
    ports:
      - 8094:80
    volumes:
      - ../../build/test-certs:/var/test-certs:ro
    restart: always
    networks:
      - interop_ecosystem_network
    extra_hosts:
      - host.docker.internal:host-gateway

  mock_uss_scdsc_interaction_log:
    container_name: mock_uss_scdsc_interaction_log
    hostname: scdsc.log.uss6.localutm
    image: interuss/monitoring
    command: mock_uss/start.sh
    environment:
      - MOCK_USS_AUTH_SPEC=DummyOAuth(${XSV_URL}/auth/token,uss6)
      - MOCK_USS_DSS_URL=${XSV_URL}
      - MOCK_USS_PUBLIC_KEY=/var/test-certs/auth2.pem
      - MOCK_USS_TOKEN_AUDIENCE=scdsc.log.uss6.localutm,localhost,host.docker.internal,${XSV_AUD:-}
      - MOCK_USS_BASE_URL=${XSV_URL}/muss_log
      - MOCK_USS_SERVICES=scdsc,interaction_logging,flight_planning
      - MOCK_USS_INTERACTIONS_LOG_DIR=output/scdsc_interaction_logs
      - MOCK_USS_PORT=80
    expose:
      - 80
    ports:
      - 8095:80
    volumes:
      - ../../build/test-certs:/var/test-certs:ro
      - ./output/scdsc_interaction_logs:/app/monitoring/mock_uss/output/scdsc_interaction_logs
    user: "${UID_GID}"
    restart: always
    networks:
      - interop_ecosystem_network
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  interop_ecosystem_network:
    external: true
